import { BiSolidStoreAlt } from "react-icons/bi";
import {
  FaHome,
  FaCar,
  FaTshirt,
  FaBriefcase,
  FaFootballBall,
  FaTools,
  FaIndustry,
  FaBabyCarriage,
} from "react-icons/fa";
import { FaMobileScreenButton, FaDog } from "react-icons/fa6";
import { SiApplearcade } from "react-icons/si";

export const navLinks = [
  {
    title: "governorates",
    link: "/discover",
    departments: [
      {
        name: "Cairo",
        link: "/",
      },
      {
        name: "Alexandria",
        link: "/",
      },
      {
        name: "Giza",
        link: "/",
      },
      {
        name: "Luxor",
        link: "/",
      },
      {
        name: "Aswan",
        link: "/",
      },
    ],
  },
  {
    title: "places",
    link: "/places",
    departments: [
      {
        name: "The Egyptian Museum",
        link: "/",
      },
      {
        name: "The Pyramids of Giza",
        link: "/",
      },
      {
        name: "Abu Simbel Temples",
        link: "/",
      },
    ],
  },
  {
    title: "Masr 360 Nights",
    link: "/nights",
    departments: [
      {
        name: "Nile Parties",
        icon: "MdOutlineCelebration",
        link: "/",
      },
      {
        name: "Safari Nights",
        icon: "MdOutlineNightlife",
        link: "/",
      },
      {
        name: "Restaurants & Cafes",
        icon: "MdRestaurant",
        link: "/",
      },
      {
        name: "Cultural Events",
        icon: "MdLocalActivity",
        link: "/",
      },
    ],
  },
  {
    title: "Marketplace",
    link: "/marketplace",
    departments: [
      { name: "Souvenirs", icon: "MdShoppingBag", link: "/" },
      { name: "Local Crafts", icon: "MdHandyman", link: "/" },
      { name: "Art & Decor", icon: "MdBrush", link: "/" },
      { name: "Traditional Clothes", icon: "MdCheckroom", link: "/" },
    ],
  },
  {
    title: "games",
    link: "/games",
  },
  {
    title: "about us",
    link: "/about",
  },
];
export const slides = [
  {
    image: "/Slides/slide-003.jpg",
    small: "Discover Egypt",
    paragraph:
      "Explore hidden gems, exciting night spots, and real Egyptian culture with dawarly. Your journey starts here — fun, local, and unforgettable.",
    title: "Live the Full Experience",
    btnText: "Explore Now",
    link: "/discover",
  },
  {
    image: "/Slides/slide-005.jpg",
    small: "Play • Explore • Win",
    paragraph:
      "Complete fun challenges at iconic places, earn points, and unlock real rewards — restaurants, handcrafts, and more!",
    title: "Make Every Step a Game",
    btnText: "See Events",
    link: "/nights",
  },
  {
    image: "/Slides/slide-001.jpg",

    small: "Explore Egypt Differently",
    paragraph:
      "Find hidden gems, unique experiences, and special rewards across all Egyptian governorates. dawarly is your smart guide to explore, play, and enjoy every part of Egypt.",
    title: "Discover the Real Egypt",
    btnText: "Visit Marketplace",
    link: "/marketplace",
  },
];
export const filterss = [
  {
    id: "properties",
    sorting: [
      {
        id: "name",
        filters: [
          {
            name: "Name: A to Z",
            value: "a_to_z",
          },
          {
            name: "Name: Z to A",
            value: "z_to_a",
          },
        ],
      },
      {
        id: "price",
        filters: [
          {
            name: "Price: Low to High",
            value: "low_to_high",
          },
          {
            name: "Price: High to Low",
            value: "high_to_low",
          },
        ],
      },

      {
        id: "date",
        filters: [
          {
            name: "Newest",
            value: "newest",
          },
          {
            name: "Oldest",
            value: "oldest",
          },
        ],
      },
    ],
  },
  {
    id: "main",
    sorting: [
      {
        id: "date",
        filters: [
          {
            name: "Newest",
            value: "newest",
          },
          {
            name: "Oldest",
            value: "oldest",
          },
        ],
      },
      {
        id: "price",
        filters: [
          {
            name: "Price: Low to High",
            value: "low_to_high",
          },
          {
            name: "Price: High to Low",
            value: "high_to_low",
          },
        ],
      },
    ],
  },
];
export const govs = [
  "Cairo",
  "Giza",
  "Alexandria",
  "Dakahlia",
  "Red Sea",
  "Beheira",
  "Fayoum",
  "Gharbia",
  "Ismailia",
  "Menofia",
  "Minya",
  "Qaliubiya",
  "New Valley",
  "Suez",
  "Aswan",
  "Assiut",
  "Bani Sweif",
  "Port Said",
  "Damietta",
  "Sharkia",
  "South Sinai",
  "Kafr El Sheikh",
  "Matrouh",
  "Luxor",
  "Qena",
  "North Sinai",
  "Sohag",
];
export const categories = [
  {
    id: 1,
    key: "properties",
    name: { en: "Properties", ar: "عقارات" },
    icon: BiSolidStoreAlt,
  },
  {
    id: 2,
    key: "vehicles",
    name: { en: "Vehicles", ar: "مركبات" },
    icon: FaCar,
  },
  {
    id: 3,
    key: "mobiles-tablets",
    name: { en: "Mobiles & Tablets", ar: "موبايلات وتابلت" },
    icon: FaMobileScreenButton,
  },
  {
    id: 4,
    key: "electronics",
    name: { en: "Electronics", ar: "إلكترونيات" },
    icon: SiApplearcade,
  },
  {
    id: 5,
    key: "home-office",
    name: { en: "Home & Office", ar: "المنزل والمكتب" },
    icon: FaHome,
  },
  {
    id: 6,
    key: "fashion",
    name: { en: "Fashion", ar: "أزياء" },
    icon: FaTshirt,
  },
  {
    id: 7,
    key: "jobs",
    name: { en: "Jobs", ar: "وظائف" },
    icon: FaBriefcase,
  },
  {
    id: 8,
    key: "services",
    name: { en: "Services", ar: "خدمات" },
    icon: FaTools,
  },
  {
    id: 9,
    key: "pets",
    name: { en: "Pets", ar: "حيوانات أليفة" },
    icon: FaDog,
  },
  {
    id: 10,
    key: "kids-babies",
    name: { en: "Kids & Babies", ar: "أطفال ورضع" },
    icon: FaBabyCarriage,
  },
  {
    id: 11,
    key: "sports-hobbies",
    name: { en: "Sports & Hobbies", ar: "رياضة وهوايات" },
    icon: FaFootballBall,
  },
  {
    id: 12,
    key: "business-industrial",
    name: { en: "Business & Industrial", ar: "أعمال وصناعة" },
    icon: FaIndustry,
  },
];
export const subcategories = [
  // ========= Properties =========
  {
    id: 101,
    categoryId: 1,
    name: { en: "Apartments for Sale", ar: "شقق للبيع" },
  },
  {
    id: 102,
    categoryId: 1,
    name: { en: "Apartments for Rent", ar: "شقق للإيجار" },
  },
  { id: 103, categoryId: 1, name: { en: "Villas", ar: "فيلات" } },
  { id: 104, categoryId: 1, name: { en: "Commercial", ar: "عقارات تجارية" } },
  { id: 105, categoryId: 1, name: { en: "Lands", ar: "أراضي" } },

  // ========= Vehicles =========
  { id: 201, categoryId: 2, name: { en: "Cars", ar: "سيارات" } },
  { id: 202, categoryId: 2, name: { en: "Motorcycles", ar: "دراجات نارية" } },
  { id: 203, categoryId: 2, name: { en: "Spare Parts", ar: "قطع غيار" } },
  {
    id: 204,
    categoryId: 2,
    name: { en: "Heavy Vehicles", ar: "مركبات ثقيلة" },
  },

  // ========= Mobiles & Tablets =========
  { id: 301, categoryId: 3, name: { en: "Mobile Phones", ar: "موبايلات" } },
  { id: 302, categoryId: 3, name: { en: "Tablets", ar: "تابلت" } },
  { id: 303, categoryId: 3, name: { en: "Accessories", ar: "إكسسوارات" } },

  // ========= Electronics =========
  {
    id: 401,
    categoryId: 4,
    name: { en: "TV & Audio", ar: "تلفزيونات وصوتيات" },
  },
  { id: 402, categoryId: 4, name: { en: "Computers", ar: "كمبيوتر" } },
  { id: 403, categoryId: 4, name: { en: "Video Games", ar: "ألعاب فيديو" } },
  { id: 404, categoryId: 4, name: { en: "Cameras", ar: "كاميرات" } },

  // ========= Home & Office =========
  { id: 501, categoryId: 5, name: { en: "Furniture", ar: "أثاث" } },
  {
    id: 502,
    categoryId: 5,
    name: { en: "Office Furniture", ar: "أثاث مكتبي" },
  },
  { id: 503, categoryId: 5, name: { en: "Home Decor", ar: "ديكور" } },

  // ========= Fashion =========
  { id: 601, categoryId: 6, name: { en: "Men Clothing", ar: "ملابس رجالي" } },
  { id: 602, categoryId: 6, name: { en: "Women Clothing", ar: "ملابس حريمي" } },
  { id: 603, categoryId: 6, name: { en: "Shoes & Bags", ar: "أحذية وشنط" } },

  // ========= Jobs =========
  {
    id: 701,
    categoryId: 7,
    name: { en: "Full Time Jobs", ar: "وظائف دوام كامل" },
  },
  {
    id: 702,
    categoryId: 7,
    name: { en: "Part Time Jobs", ar: "وظائف دوام جزئي" },
  },
  { id: 703, categoryId: 7, name: { en: "Freelance", ar: "عمل حر" } },

  // ========= Services =========
  { id: 801, categoryId: 8, name: { en: "Home Services", ar: "خدمات منزلية" } },
  { id: 802, categoryId: 8, name: { en: "Education", ar: "تعليم" } },
  { id: 803, categoryId: 8, name: { en: "Repair Services", ar: "صيانة" } },

  // ========= Pets =========
  { id: 901, categoryId: 9, name: { en: "Dogs", ar: "كلاب" } },
  { id: 902, categoryId: 9, name: { en: "Cats", ar: "قطط" } },
  {
    id: 903,
    categoryId: 9,
    name: { en: "Pet Accessories", ar: "مستلزمات حيوانات" },
  },

  // ========= Kids & Babies =========
  { id: 1001, categoryId: 10, name: { en: "Toys", ar: "ألعاب" } },
  { id: 1002, categoryId: 10, name: { en: "Clothes", ar: "ملابس أطفال" } },
  { id: 1003, categoryId: 10, name: { en: "Baby Gear", ar: "مستلزمات رضع" } },

  // ========= Sports & Hobbies =========
  {
    id: 1101,
    categoryId: 11,
    name: { en: "Sports Equipment", ar: "معدات رياضية" },
  },
  { id: 1102, categoryId: 11, name: { en: "Bicycles", ar: "دراجات" } },
  {
    id: 1103,
    categoryId: 11,
    name: { en: "Musical Instruments", ar: "آلات موسيقية" },
  },

  // ========= Business & Industrial =========
  {
    id: 1201,
    categoryId: 12,
    name: { en: "Industrial Equipment", ar: "معدات صناعية" },
  },
  {
    id: 1202,
    categoryId: 12,
    name: { en: "Office Equipment", ar: "معدات مكتبية" },
  },
  { id: 1203, categoryId: 12, name: { en: "Wholesale", ar: "جملة" } },
];

// =============================
// Users (15 Egyptian fake users)
// =============================

export const users = [
  {
    id: "u_001",
    first_name: "محمد",
    last_name: "علي",
    email: "m.ali@gmail.com",
    phone: "+201001112233",
    image: "/images/users/u1.png",
    settings: { language: "ar", theme: "dark" },
    saved_listings: [101, 105],
    region: { governorate: "Cairo", city: "Nasr City" },
  },
  {
    id: "u_002",
    first_name: "Ahmed",
    last_name: "Hassan",
    email: "ahmed.hassan@gmail.com",
    phone: "+201022334455",
    image: "/images/users/u2.png",
    settings: { language: "en", theme: "light" },
    saved_listings: [102, 110],
    region: { governorate: "Giza", city: "Dokki" },
  },
  {
    id: "u_003",
    first_name: "محمود",
    last_name: "السيد",
    email: "mahmoud@gmail.com",
    phone: "+201055667788",
    image: "/images/users/u3.png",
    settings: { language: "ar", theme: "dark" },
    saved_listings: [],
    region: { governorate: "Alexandria", city: "Smouha" },
  },
  {
    id: "u_004",
    first_name: "Sara",
    last_name: "Mostafa",
    email: "sara@gmail.com",
    phone: "+201066778899",
    image: "/images/users/u4.png",
    settings: { language: "en", theme: "light" },
    saved_listings: [103],
    region: { governorate: "Cairo", city: "Heliopolis" },
  },
  {
    id: "u_005",
    first_name: "يوسف",
    last_name: "إبراهيم",
    email: "yousef@gmail.com",
    phone: "+201099887766",
    image: "/images/users/u5.png",
    settings: { language: "ar", theme: "dark" },
    saved_listings: [104, 106],
    region: { governorate: "Giza", city: "Sheikh Zayed" },
  },
  {
    id: "u_006",
    first_name: "Omar",
    last_name: "Fathy",
    email: "omar@gmail.com",
    phone: "+201011223344",
    image: "/images/users/u6.png",
    settings: { language: "en", theme: "dark" },
    saved_listings: [107],
    region: { governorate: "Cairo", city: "Maadi" },
  },
  {
    id: "u_007",
    first_name: "منى",
    last_name: "حسين",
    email: "mona@gmail.com",
    phone: "+201044556677",
    image: "/images/users/u7.png",
    settings: { language: "ar", theme: "light" },
    saved_listings: [],
    region: { governorate: "Giza", city: "Haram" },
  },
  {
    id: "u_008",
    first_name: "Khaled",
    last_name: "Samir",
    email: "khaled@gmail.com",
    phone: "+201077889900",
    image: "/images/users/u8.png",
    settings: { language: "en", theme: "dark" },
    saved_listings: [108],
    region: { governorate: "Cairo", city: "New Cairo" },
  },
  {
    id: "u_009",
    first_name: "Heba",
    last_name: "Nasser",
    email: "heba@gmail.com",
    phone: "+201088776655",
    image: "/images/users/u9.png",
    settings: { language: "en", theme: "light" },
    saved_listings: [109],
    region: { governorate: "Alexandria", city: "Stanley" },
  },
  {
    id: "u_010",
    first_name: "عبدالله",
    last_name: "سعيد",
    email: "abdullah@gmail.com",
    phone: "+201033221100",
    image: "/images/users/u10.png",
    settings: { language: "ar", theme: "dark" },
    saved_listings: [],
    region: { governorate: "Dakahlia", city: "Mansoura" },
  },
  {
    id: "u_011",
    first_name: "Nour",
    last_name: "Adel",
    email: "nour@gmail.com",
    phone: "+201055443322",
    image: "/images/users/u11.png",
    settings: { language: "en", theme: "light" },
    saved_listings: [111],
    region: { governorate: "Cairo", city: "Shubra" },
  },
  {
    id: "u_012",
    first_name: "ريم",
    last_name: "فتحي",
    email: "reem@gmail.com",
    phone: "+201066554433",
    image: "/images/users/u12.png",
    settings: { language: "ar", theme: "light" },
    saved_listings: [],
    region: { governorate: "Giza", city: "Faisal" },
  },
  {
    id: "u_013",
    first_name: "Tamer",
    last_name: "Youssef",
    email: "tamer@gmail.com",
    phone: "+201077665544",
    image: "/images/users/u13.png",
    settings: { language: "en", theme: "dark" },
    saved_listings: [112],
    region: { governorate: "Sharqia", city: "Zagazig" },
  },
  {
    id: "u_014",
    first_name: "إيمان",
    last_name: "عبدالرحمن",
    email: "eman@gmail.com",
    phone: "+201088990011",
    image: "/images/users/u14.png",
    settings: { language: "ar", theme: "light" },
    saved_listings: [],
    region: { governorate: "Cairo", city: "Ain Shams" },
  },
  {
    id: "u_015",
    first_name: "Mahmoud",
    last_name: "Kamel",
    email: "mkamel@gmail.com",
    phone: "+201099001122",
    image: "/images/users/u15.png",
    settings: { language: "en", theme: "dark" },
    saved_listings: [113, 114],
    region: { governorate: "Ismailia", city: "Ismailia" },
  },
];

// =============================
// Amenities (Shared objects)
// =============================

export const amenities = [
  { id: 1, key: "balcony", name: { en: "Balcony", ar: "بلكونة" } },
  { id: 2, key: "gym", name: { en: "Gym", ar: "جيم" } },
  { id: 3, key: "parking", name: { en: "Parking", ar: "جراج" } },
  { id: 4, key: "elevator", name: { en: "Elevator", ar: "مصعد" } },
  { id: 5, key: "security", name: { en: "Security", ar: "أمن" } },
];

// =============================
// Ads / Listings (15 ads | owned by 5 users)
// =============================

export const ads = [
  // ===== User u_001 =====
  {
    id: 101,
    user_id: "u_001",
    title: "شقة للبيع في مدينة نصر",
    description: "شقة 110 متر قريبة من الخدمات",
    price: 1850000,
    negotiable: true,
    category: { id: 1, key: "properties" },
    sub_category: { id: 101, name: "Apartments for Sale" },
    status: "for sale",
    condition: null,
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Cairo", city: "Nasr City" },
    specs: { area_m2: 110, bedrooms: 2, bathrooms: 2, furnished: false },
    amenities: [amenities[0], amenities[3]],
    images: ["/ads/ap1.jpg"],
    tags: ["شقة", "تمليك"],
    creation_date: "2025-12-10",
  },
  {
    id: 102,
    user_id: "u_001",
    title: "iPhone 13 Pro Max",
    description: "256GB – حالة ممتازة",
    price: 28500,
    negotiable: false,
    category: { id: 3, key: "mobiles-tablets" },
    sub_category: { id: 301, name: "Mobile Phones" },
    status: null,
    condition: "used",
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Cairo", city: "Nasr City" },
    specs: { storage_gb: 256, battery_health_percent: 92 },
    amenities: [],
    images: ["/ads/iphone3.jpeg"],
    tags: ["iphone", "apple"],
    creation_date: "2025-12-19",
  },
  {
    id: 103,
    user_id: "u_001",
    title: "كنبة مودرن 3 مقاعد",
    description: "خشب زان – حالة جيدة",
    price: 7500,
    negotiable: true,
    category: { id: 5, key: "home-office" },
    sub_category: { id: 501, name: "Furniture" },
    status: null,
    condition: "used",
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Cairo", city: "Nasr City" },
    specs: { material: "wood", seats: 3 },
    amenities: [],
    images: ["/ads/sofa1.jpg"],
    tags: ["كنبة", "أثاث"],
    creation_date: "2025-12-19 18:30:59.561",
  },

  // ===== User u_002 =====
  {
    id: 104,
    user_id: "u_002",
    title: "Hyundai Elantra 2019",
    description: "فابريكا بالكامل",
    price: 720000,
    negotiable: true,
    category: { id: 2, key: "vehicles" },
    sub_category: { id: 201, name: "Cars" },
    status: "for sale",
    condition: null,
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Giza", city: "Dokki" },
    specs: { model_year: 2019, km: 85000, transmission: "automatic" },
    amenities: [],
    images: ["/ads/car1.jpg"],
    tags: ["hyundai", "car"],
    creation_date: "2025-01-10",
  },
  {
    id: 105,
    user_id: "u_002",
    title: "موتوسيكل هوجن 200",
    description: "جاهز للاستخدام",
    price: 68000,
    negotiable: true,
    category: { id: 2, key: "vehicles" },
    sub_category: { id: 202, name: "Motorcycles" },
    status: "for sale",
    condition: null,
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Giza", city: "Dokki" },
    specs: { engine_cc: 200 },
    amenities: [],
    images: ["/ads/bike1.jpg"],
    tags: ["motorcycle"],
    creation_date: "2025-01-12",
  },
  {
    id: 106,
    user_id: "u_002",
    title: "لابتوب Dell Latitude",
    description: "i7 – رام 16 جيجا",
    price: 19500,
    negotiable: false,
    category: { id: 4, key: "electronics" },
    sub_category: { id: 402, name: "Computers" },
    status: null,
    condition: "used",
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Giza", city: "Dokki" },
    specs: { cpu: "i7", ram_gb: 16 },
    amenities: [],
    images: ["/ads/laptop1.webp"],
    tags: ["dell", "laptop"],
    creation_date: "2025-01-13",
  },

  // ===== User u_003 =====
  {
    id: 107,
    user_id: "u_003",
    title: "شقة للإيجار في سموحة",
    description: "تشطيب سوبر لوكس",
    price: 12000,
    negotiable: false,
    category: { id: 1, key: "properties" },
    sub_category: { id: 102, name: "Apartments for Rent" },
    status: "for rent",
    condition: null,
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Alexandria", city: "Smouha" },
    specs: { area_m2: 95, bedrooms: 2, bathrooms: 1, furnished: true },
    amenities: [amenities[0], amenities[4]],
    images: ["/ads/ap2.webp"],
    tags: ["إيجار", "سموحة"],
    creation_date: "2025-01-11",
  },
  {
    id: 108,
    user_id: "u_003",
    title: "Samsung Galaxy S22",
    description: "زي الجديد",
    price: 19000,
    negotiable: false,
    category: { id: 3, key: "mobiles-tablets" },
    sub_category: { id: 301, name: "Mobile Phones" },
    status: null,
    condition: "like new",
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Alexandria", city: "Smouha" },
    specs: { storage_gb: 128 },
    amenities: [],
    images: ["/ads/mobile1..jpg"],
    tags: ["samsung"],
    creation_date: "2025-01-12",
  },
  {
    id: 109,
    user_id: "u_003",
    title: "ترابيزة سفرة 6 كراسي",
    description: "خشب طبيعي",
    price: 9800,
    negotiable: true,
    category: { id: 5, key: "home-office" },
    sub_category: { id: 501, name: "Furniture" },
    status: null,
    condition: "used",
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Alexandria", city: "Smouha" },
    specs: { seats: 6 },
    amenities: [],
    images: ["/ads/table1.jpeg"],
    tags: ["سفرة"],
    creation_date: "2025-01-13",
  },

  // ===== User u_004 =====
  {
    id: 110,
    user_id: "u_004",
    title: "فستان سواريه",
    description: "لبسة واحدة",
    price: 3500,
    negotiable: true,
    category: { id: 6, key: "fashion" },
    sub_category: { id: 602, name: "Women Clothing" },
    status: null,
    condition: "like new",
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Cairo", city: "Heliopolis" },
    specs: { size: "M" },
    amenities: [],
    images: ["/ads/dress1.jpg"],
    tags: ["فستان"],
    creation_date: "2025-01-11",
  },
  {
    id: 111,
    user_id: "u_004",
    title: "قط شيرازي",
    description: "مطعم وجاهز",
    price: 2500,
    negotiable: false,
    category: { id: 9, key: "pets" },
    sub_category: { id: 902, name: "Cats" },
    status: null,
    condition: "new",
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Cairo", city: "Heliopolis" },
    specs: { age_months: 3 },
    amenities: [],
    images: ["/ads/cat1.webp"],
    tags: ["قطط"],
    creation_date: "2025-01-12",
  },
  {
    id: 112,
    user_id: "u_004",
    title: "وظيفة خدمة عملاء",
    description: "دوام كامل",
    price: 0,
    negotiable: false,
    category: { id: 7, key: "jobs" },
    sub_category: { id: 701, name: "Full Time Jobs" },
    status: null,
    condition: null,
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Cairo", city: "Heliopolis" },
    specs: { salary_range: "6000-8000" },
    amenities: [],
    images: ["/ads/job1.jpg"],
    tags: ["وظيفة"],
    creation_date: "2025-01-13",
  },

  // ===== User u_005 =====
  {
    id: 113,
    user_id: "u_005",
    title: "محل للإيجار",
    description: "موقع مميز",
    price: 15000,
    negotiable: true,
    category: { id: 1, key: "properties" },
    sub_category: { id: 104, name: "Commercial" },
    status: "for rent",
    condition: null,
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Giza", city: "Sheikh Zayed" },
    specs: { area_m2: 60 },
    amenities: [amenities[4]],
    images: ["/ads/shop1.jpg"],
    tags: ["محل"],
    creation_date: "2025-01-11",
  },
  {
    id: 114,
    user_id: "u_005",
    title: "PlayStation 5",
    description: "بحالة ممتازة",
    price: 24000,
    negotiable: false,
    category: { id: 4, key: "electronics" },
    sub_category: { id: 403, name: "Video Games" },
    status: null,
    condition: "used",
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Giza", city: "Sheikh Zayed" },
    specs: { storage_gb: 825 },
    amenities: [],
    images: ["/ads/ps5.jpg"],
    tags: ["ps5"],
    creation_date: "2025-12-12",
  },
  {
    id: 115,
    user_id: "u_005",
    title: "خدمة تنظيف منازل",
    description: "خبرة 5 سنوات",
    price: 300,
    negotiable: true,
    category: { id: 8, key: "services" },
    sub_category: { id: 801, name: "Home Services" },
    status: null,
    condition: null,
    location: "https://maps.app.goo.gl/yjMxu9toMPVHXP7x6",
    area: { governorate: "Giza", city: "Sheikh Zayed" },
    specs: { service_type: "cleaning" },
    amenities: [],
    images: ["/ads/service1.jpg"],
    tags: ["تنظيف"],
    creation_date: "2025-01-13",
  },
];
